# Generated by Django 4.0.1 on 2022-01-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='updt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nname', models.CharField(default='', max_length=20)),
                ('nemail', models.CharField(default='', max_length=20)),
                ('npassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='user1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(default='', max_length=20)),
                ('members', models.CharField(default='', max_length=20)),
                ('ptech', models.CharField(max_length=30)),
                ('deadline', models.CharField(default='', max_length=20)),
                ('vcont', models.CharField(default='', max_length=20)),
                ('cicd', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
