# Generated by Django 4.0.1 on 2022-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addgit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gitplat', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='addtech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techname', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='updt',
        ),
    ]
