# Generated by Django 4.0.1 on 2022-01-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_addgit_addtech_delete_updt'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30, null=True)),
                ('technologies_used', models.CharField(max_length=30, null=True)),
                ('git_platform', models.CharField(max_length=30, null=True)),
                ('project_deadline', models.IntegerField(default=60)),
            ],
        ),
    ]
