# Generated by Django 4.0.1 on 2022-01-21 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addgit',
            name='id',
        ),
        migrations.AddField(
            model_name='addgit',
            name='git_id',
            field=models.BigAutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
