# Generated by Django 4.0.1 on 2022-01-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_remove_addgit_id_addgit_git_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addgit',
            name='git_id',
        ),
        migrations.AddField(
            model_name='addgit',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
