# Generated by Django 4.0.1 on 2022-01-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_remove_addgit_git_id_addgit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addgit',
            name='id',
        ),
        migrations.AddField(
            model_name='addgit',
            name='git_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
