# Generated by Django 4.0.1 on 2022-01-21 10:43

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_remove_addgit_id_addgit_git_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addgit',
            name='git_id',
        ),
        migrations.AddField(
            model_name='addgit',
            name='ID',
            field=models.BigAutoField(default=random.Random.randint, primary_key=True, serialize=False),
        ),
    ]
